### ISSUE TITLE
Load AMP version automatically

### ISSUE THREAD

**Issue by niutech** [jpettitt/amplifier#1]
Please add an option to load the AMP version of a web page automatically in order to save data and improve page load time.

**Comment by jpettitt** [comment]
I won't be implementing that for now.  Loading the AMP version requires loading the canonical version to detect the amphtml header so what you propose would actually increase data consumption and load time.

**Comment by niutech** [comment]
You're right. If only chrome.webRequest allowed to read response body,
it would be possible.

**Comment by niutech** [comment]
I have just submitted PR #2 which loads the content script on the document start and stops loading the page as soon as it redirects to the AMP link, thus minimizing the overhead. Please check it out.
